name: Hello-World-Test

on: [pull_request]

jobs:
  build:
    name: Testing basic hello-world command
    runs-on: ubuntu-20.04
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: build-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: python-wheel
        run: |
          (cd rhdzmota; python setup.py bdist_wheel)
      - name: rhdzmota-install
        run: |
          python -m pip install rhdzmota/dist/rhdzmota*.whl
      - name: hello-world
        run: |
          python -m rhdzmota hello
