name: PyPI Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - PRD

jobs:
  build:
    # Check if PR was closed due to a merge.
    if: github.event.pull_request.merged == true
    # Create a job on Ubuntu 18.04
    name: Build & Publish!
    runs-on: ubuntu-20.04
    steps:
      # Copy github repo with submodules
      - name: clone-repo
        uses: actions/checkout@v4
        with:
          submodules: true
      # Install python
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: install-twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
      # Build and publish!
      - name: build-and-publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          (cd rhdzmota; python setup.py sdist)
          twine upload -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} --skip-existing rhdzmota/dist/*
